name: Automated Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
=======

      - name: Checkout repository
        uses: actions/checkout@v4

 
>>>>>>> e08c6d129129048088638a7045feef86b4b30a0c
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

<<<<<<< HEAD
      # 3. Install dependencies
=======
 
>>>>>>> e08c6d129129048088638a7045feef86b4b30a0c
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib matplotlib

<<<<<<< HEAD
      # 4. Run preprocessing script
=======
 
>>>>>>> e08c6d129129048088638a7045feef86b4b30a0c
      - name: Run preprocessing script
        run: |
          python preprocessing/automate_oryzasativa.py

<<<<<<< HEAD
      # 5. Move processed data (opsional, kalau script sudah simpan di folder tertentu)
=======

>>>>>>> e08c6d129129048088638a7045feef86b4b30a0c
      - name: Move processed data
        run: |
          mv train_preprocessing.csv preprocessing/
          mv test_preprocessing.csv preprocessing/

<<<<<<< HEAD
      # 6. Commit & Push processed data
=======

>>>>>>> e08c6d129129048088638a7045feef86b4b30a0c
      - name: Commit processed data
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add preprocessing/train_preprocessing.csv preprocessing/test_preprocessing.csv
          git commit -m "Update preprocessed data" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/oryzava/Eksperimen_SML_OryzaSativa.git HEAD:main
